name: Super Mario
on:
   push:
   workflow_dispatch: 
    
jobs:
    connect_to_ssh:
      name: Checkout code
      runs-on: ubuntu-latest
      steps:
        - name: pre-reqs for SSH
          run: |
            install -m 600 -D /dev/null ~/.ssh/id_rsa
            echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
            ssh-keyscan -H ${{ secrets.SSH_HOST }} > ~/.ssh/known_hosts
            ls -lart ~/.ssh/
        - name: connect and pull
          run: ssh -i ~/.ssh/id_rsa ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "ls -lart"

